// <auto-generated />
using System;
using AspNetCoreTodo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreTodo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("AspNetCoreTodo.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("DueAt");

                    b.Property<bool>("IsDone");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fad3c24e-7453-490e-8af9-d3b728393182"),
                            DueAt = new DateTimeOffset(new DateTime(2019, 7, 20, 20, 18, 46, 503, DateTimeKind.Unspecified).AddTicks(4717), new TimeSpan(0, -3, 0, 0, 0)),
                            IsDone = false,
                            Title = "Curso ASP.NET Core UTN"
                        },
                        new
                        {
                            Id = new Guid("b5b82700-e41e-43c4-b6da-39e19ac54403"),
                            DueAt = new DateTimeOffset(new DateTime(2019, 7, 20, 20, 18, 46, 506, DateTimeKind.Unspecified).AddTicks(8779), new TimeSpan(0, -3, 0, 0, 0)),
                            IsDone = false,
                            Title = "Curso React"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
